# Generated by Django 4.2.1 on 2025-03-15 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('admission_number', models.CharField(blank=True, max_length=10, unique=True)),
                ('date_of_admission', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransferCertificate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tc_file', models.FileField(upload_to='transfer_certificates/')),
                ('issued_date', models.DateField(auto_now_add=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_certificate', to='student.student')),
            ],
            options={
                'db_table': 'transfer_certificates',
            },
        ),
    ]
