# Generated by Django 4.2.1 on 2025-03-17 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_updates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
